name: Calculator
main: xyz.tangledwires.calculator.Calculator
version: 0.0.2
author: YT_TangledWires
commands:
   add:
      description: Add two numbers together.
      usage: /add [int] [int]
      permission: calculator.add
      permission-message: You don't have permission to use this command!