name: Calculator
main: xyz.tangledwires.calculator.Calculator
version: 1.1.0
author: YT_TangledWires
commands:
   add:
      description: Add two numbers together.
      usage: /add [int] [int]
      permission: calculator.add
      permission-message: You don't have permission to use this command!
   subtract:
      description: Subtract the seconds number from the first.
      usage: /subtract [int] [int]
      permission: calculator.subtract
      permission-message: You don't have permission to use this command!