name: Calculator
main: xyz.tangledwires.calculator.Calculator
version: 1.2.1
author: YT_TangledWires
commands:
   add:
      description: Add two numbers together.
      usage: /add [int] [int]
      permission: calculator.add
      permission-message: You don't have permission to use this command!
   subtract:
      description: Subtract the second number from the first.
      usage: /subtract [int] [int]
      permission: calculator.subtract
      permission-message: You don't have permission to use this command!
   multiply:
      description: Multiply the first number by the second.
      usage: /multiply [int] [int]
      permission: calculator.multiply
      permission-message: You don't have permission to use this command!
   divide:
      description: Divide the first number by the second.
      usage: /divide [int] [int]
      permission: calculator.divide
      permission-message: You don't have permission to use this command!